var express = require('express')
var router =express.Router();

module.exports={
    getsignin:async(req,res)=>{
        try{
            res.render('admin/signin')
        }catch(error){
            console.log(error);
        }
    },
    getsignup:async(req,res)=>{
        try{
            res.render('admin/signup')
        }catch(error){
            console.log(error)
        }
    },
    gettable:async(req,res)=>{
        try{
            res.render('admin/table')
        }catch(error){
            console.log(error);
        }
    },
    getindex:async(req,res)=>{
        try{
            res.render('admin/index')
        }catch(error){
            console.log(error);
        }
    },
    getwidget:async(req,res)=>{
        try{
            res.render('admin/widget')
        }catch(error){
            console.log(error);
        }
    },
    gettypography:async(req,res)=>{
        try{
            res.render('admin/typography')
        }catch(error){
            console.log(error);
        }
    },
    getform:async(req,res)=>{
        try{
            res.render('admin/form')
        }catch(error){
            console.log(error);
        }
    },
    getelement:async(req,res)=>{
        try{
            res.render('admin/element')
        }catch(error){
            console.log(error);
        }
    },
    getchart:async(req,res)=>{
        try{
            res.render('admin/chart')
        }catch(error){
            console.log(error);
        }
    },
    getbutton:async(req,res)=>{
    try{
        res.render('admin/button')
    }catch(error){
        console.log(error);
    }
   },
   getblank:async(req,res)=>{
    try{
        res.render('admin/blank')
    }catch(error){
        console.log(error);
    }
   },
   get404:async(req,res)=>{
    try{
        res.render('admin/404')
    }catch(error){
        console.log(error);
    }
   }
}